#!/bin/sh

function handle {
  if [[ ${1:0:9} == "workspace" ]] || [[ ${1:0:13} == "moveworkspace" ]]; then
    python3 $HOME/.config/eww/scripts/workspace
  fi
}

python3 $HOME/.config/eww/scripts/workspace
socat -u "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - | while read -r line; do handle "$line"; done
